name: nuvilab_assignment
description: "nuvilab assignment"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.3
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_riverpod: ^2.6.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
